name: Build & Deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Rental Service App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_PRIV_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd /var/www/signcast/signcast-dashboard
            git checkout .
            git checkout master
            git reset --hard origin/master
            git pull
            echo 'Success'
